version: '3.1'

services:

  mongo:
    image: mongo
    container_name: nodets
    restart: always
    ports: 
      - 27017:27017
      
    # volumes:
    #   - ./data/db:/data/db

    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: pass
